# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "MAP::API"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

#template: "simple"

template: "template_toolkit"
#	engines:
#		template_toolkit:
#			extension: 'html'
#     		start_tag: '[%'
#     		end_tag:   '%]'


plugins:
    Database:
        driver: 'Sybase'
        database: 'MAPTEST'
        host: '192.168.1.19'
        #port: 1433
        username: 'ESCairs'
        password: 'FishB8'
        connection_check_threshold: 10
        dbi_params:
            RaiseError: 1
            AutoCommit: 1
        on_connect_do: ["use MAPTEST;" ]
        log_queries: 1
        #dsn: 'DBI:Sybase:server=192.168.1.15'

environment: deployment
